// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_GLOSSY_H
#define LUX_GLOSSY_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				Kd;				// color
	miColor             Ks;				// color
    miColor             Kt;             // color
    miBoolean           multibounce;    // boolean
    miScalar        	index;          // scalar
    miScalar            uroughness;
	miScalar            vroughness;
    miScalar            sigma;
    miBoolean           translucent;
    miBoolean           onesided;
} lux_glossy_t;

#endif // LUX_GLOSSY_H
