// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_SCATTER_H
#define LUX_SCATTER_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				Kd;			// color
    miScalar            g;
} lux_scatter_t;

#endif // LUX_SCATTER_H
