// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_SHINYMETAL_H
#define LUX_SHINYMETAL_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				kr;				// color
	miColor				ks;				// color
	miScalar			sigma;			// Transmit
	miScalar			roughness;
} lux_shinymetal_t;

#endif // LUX_SHINYMETAL_H
