// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_MATTETRANSLUCENT_H
#define LUX_MATTETRANSLUCENT_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				kd;				// color
	miScalar			sigma;			// Transmit
} lux_mattetranslucent_t;

#endif // LUX_MATTETRANSLUCENT_H
