// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_ROUGHGLASS_H
#define LUX_ROUGHGLASS_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				Kr;				// color
	miColor				Kt;				// color
	miScalar			uroughness;		// scalar
	miScalar			vroughness;		// scalar
	miScalar			index;			// Transmit
	miScalar			cauchyb;
	miBoolean			dispersion;		//
} lux_roughglass_t;

#endif // LUX_ROUGHGLASS_H
