// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_MIRROR_H
#define LUX_MIRROR_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				kr;				// color
} lux_mirror_t;

#endif // LUX_MIRROR_H
