// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_GLASS_H
#define LUX_GLASS_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				kr;				// color
	miColor				kt;				// color
	miScalar			index;			// Transmit
	miScalar			cauchyb;
	miBoolean			architectural;
} lux_glass_t;

#endif // LUX_GLASS_H
