// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_SUBSTRATE_H
#define LUX_SUBSTRATE_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				kd;				// color
	miColor				ks;				// color
	miScalar			sigma;			// Transmit
	miScalar			uroughness;
	miScalar			vroughness;
} lux_substrate_t;

#endif // LUX_SUBSTRATE_H
