// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_CAR_PAINT_H
#define LUX_CAR_PAINT_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				kd;					// Base color
	miColor				spec;				// Specular primary
	miColor				spec_sec;			// Specular secondary
	miColor				reflectivity;		// Reflectivity color
	miScalar			m1;					// M1
	miScalar			m2;					// M2
	miScalar			m3;					// M3
	miScalar			r1;					// R1
	miScalar			r2;					// R2
	miScalar			r3;					// R3
} lux_car_paint_t;

#endif // LUX_CAR_PAINT_H
