// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_MATTE_H
#define LUX_MATTE_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				kd;				// color
	miScalar			sigma;			// Transmit
} lux_matte_t;

#endif // LUX_MATTE_H
