// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_VELVET_H
#define LUX_VELVET_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				kd;				// color
	miScalar	 thickness;             // scalar
	miScalar			p1;
	miScalar			p2;
	miScalar			p3;
} lux_velvet_t;

#endif // LUX_VELVET_H
