// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_EMITTER_MAT_H
#define LUX_EMITTER_MAT_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miColor				color;				// Color
	miScalar			importance;			// Importance
	miScalar			gain;				// Gain
	miScalar			power;				// Power
	miScalar			efficacy;			// Efficacy
	int					nsamples;			// Samples
} lux_emitter_mat_t;

#endif // LUX_EMITTER_MAT_H
