// C Header File Generated by Softimage Shader Wizard

#ifndef LUX_METAL_H
#define LUX_METAL_H

#include <shader.h>

////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
    miTag				mname;				// color
	miScalar			roughness;		// Transmit
} lux_metal_t;

#endif // LUX_METAL_H
