// C++ Source Code Generated by Softimage Shader Wizard

////////////////////////////////////////////////////////////////
// Includes

#include <shader.h>
#include "include\lux_glossy.h"

////////////////////////////////////////////////////////////////
// Implementation

extern "C" DLLEXPORT miBoolean
lux_glossy
(
        miColor                 *result,
        miState                 *state,
        lux_glossy_t            *params
        )
{
        // TODO: Shader main code goes here
        *result = *mi_eval_color(&params->Kd);
        *result = *mi_eval_color(&params->Ks);
        return( miTRUE );
}


extern "C" DLLEXPORT void
lux_glossy_init
(
        miState                         *state,
        lux_glossy_t                    *params,
        miBoolean                       *inst_init_req
        )
{
        if( params == NULL )
        {
                // TODO: Shader global initialization code goes here (if needed)

                // Request a per-instance shader initialization as well (set to miFALSE if not needed)
                *inst_init_req = miTRUE;
        }
        else
        {
                // TODO: Shader instance-specific initialization code goes here (if needed)
        }
}


extern "C" DLLEXPORT void
lux_glossy_exit
(
        miState                 *state,
        lux_glossy_t            *params
        )
{
        if( params == NULL )
        {
                // TODO: Shader global cleanup code goes here (if needed)
        }
        else
        {
                // TODO: Shader instance-specific cleanup code goes here (if needed)
        }
}


extern "C" DLLEXPORT int
lux_glossy_version( )
{
        return( 1 );
}
